version: "2"
services:
    site:
        image: dgisolfi/bushmen-site:latest
        ports:
            - "82:80"
        depends_on:
            - db
        networks:
            - default

    db:
        image: mysql:5.7.13
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "./db/master.sql:/docker-entrypoint-initdb.d/master.sql"
            - "./db/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh"
        environment:
            MYSQL_DATABASE: null
            MYSQL_USER: null
            MYSQL_PASSWORD: null
            MYSQL_ROOT_PASSWORD: null
        networks:
            - default
