version: "3"
services:
    site:
      # image: dgisolfi/bushmen-site:latest
      build: .
      ports:
        - "82:80"
      # volumes:
      #   - ./server:/server
      container_name: bushmen_dev
      depends_on:
        - db
    
    db:
      image: postgres:11
      restart: always
      ports:
        - "5432:5432"
      container_name: database
      volumes:
        - ./db/quotes.sql:/docker-entrypoint-initdb.d/quotes.sql
      hostname: "db"
      environment:
        POSTGRES_USER: daniel
        POSTGRES_PASSWORD: Red0nions
        POSTGRES_DB: bushmen