version: "3"
services:
    www:
        build: ./src/.
        ports:
            - "83:80"
        volumes:
            - ./src:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        build: ./db/.
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: null
            MYSQL_USER: null
            MYSQL_PASSWORD: null
            MYSQL_ROOT_PASSWORD: null
        networks:
            - default
